"""Docker Compose generator."""

from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan


def generate_docker_compose(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    component_ids = {c.resource_id.lower() for c in plan.components}
    has_gazebo = any("gazebo" in cid or "gz_sim" in cid or "ros_gz" in cid for cid in component_ids)
    has_cyclonedds = any("cyclonedds" in cid for cid in component_ids)
    has_fastdds = any("fastdds" in cid for cid in component_ids)

    rmw_line = ""
    if has_cyclonedds:
        rmw_line = "      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp\n"
    elif has_fastdds:
        rmw_line = "      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp\n"

    pkg_name = plan.bringup_package_name

    services = f"""services:
  robot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: openrobo_{plan.stack_name}
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
{rmw_line}      - DISPLAY=${{DISPLAY}}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
    command: ros2 launch {pkg_name} robot_bringup.launch.py
"""

    if has_gazebo:
        services += f"""
  simulation:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: openrobo_sim_{plan.stack_name}
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${{DISPLAY}}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
    command: ros2 launch {pkg_name} robot_bringup.launch.py use_sim_time:=true
"""

    compose_content = f"""# Generated by OpenRobo Workspace Generator
version: '3.8'

{services}"""

    return GeneratedFile(
        path="docker/docker-compose.yml",
        content=compose_content,
        description="Docker Compose multi-service deployment configuration",
    )
