"""Multi-stage reproducible Dockerfile generator."""

from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan

DISTRO_IMAGE_MAP = {
    "jazzy": "ros:jazzy-ros-base",
    "humble": "ros:humble-ros-base",
    "iron": "ros:iron-ros-base",
    "rolling": "ros:rolling-ros-base",
}


def generate_dockerfile(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    distro = plan.target_distro.lower()
    base_image = DISTRO_IMAGE_MAP.get(distro, f"ros:{distro}-ros-base")

    dockerfile_content = f"""# syntax=docker/dockerfile:1
# Generated by OpenRobo Workspace Generator
# Stack: {plan.stack_name} | ROS: {plan.target_distro} | Arch: {plan.target_arch}

FROM {base_image} AS base

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO={plan.target_distro}
ENV WORKSPACE=/openrobo_ws

SHELL ["/bin/bash", "-c"]

# Install essential build tools and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    && rm -rf /var/lib/apt/lists/*

# Initialize rosdep if not already initialized
RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then rosdep init; fi \
    && (rosdep update --include-eol-distros || rosdep update)

WORKDIR ${{WORKSPACE}}

# Copy workspace source manifests and setup scripts
COPY src/ ${{WORKSPACE}}/src/
COPY setup/ ${{WORKSPACE}}/setup/

# Install system dependencies and rosdep packages
RUN chmod +x ${{WORKSPACE}}/setup/*.sh && \
    ${{WORKSPACE}}/setup/install_dependencies.sh && \
    ${{WORKSPACE}}/setup/rosdep-install.sh

# Build the workspace
RUN source /opt/ros/${{ROS_DISTRO}}/setup.bash && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release

# Setup entrypoint environment
RUN echo "source /opt/ros/${{ROS_DISTRO}}/setup.bash" >> ~/.bashrc && \
    echo "source ${{WORKSPACE}}/install/setup.bash" >> ~/.bashrc

CMD ["/bin/bash"]
"""

    return GeneratedFile(
        path="docker/Dockerfile",
        content=dockerfile_content,
        description="Multi-stage reproducible Docker container environment",
    )
