"""Composite Bringup Launch Generator.

Synthesizes the main ROS 2 launch orchestration entrypoint using strictly
verified adapters and safe user parameter references.
"""

from openrobo_workspace.adapters.gazebo import get_gazebo_launch_snippet
from openrobo_workspace.adapters.nav2 import get_nav2_launch_snippet
from openrobo_workspace.adapters.ros2_control import get_ros2_control_launch_snippet
from openrobo_workspace.adapters.slam_toolbox import get_slam_toolbox_launch_snippet
from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan


def generate_bringup_launch(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    active_adapter_ids = {c.adapter_name for c in plan.components if c.has_adapter and c.adapter_name}

    snippets = []
    generic_comments = []

    if "ros2_control" in active_adapter_ids:
        snippets.append(get_ros2_control_launch_snippet())
    if "slam_toolbox" in active_adapter_ids:
        snippets.append(get_slam_toolbox_launch_snippet())
    if "nav2" in active_adapter_ids:
        snippets.append(get_nav2_launch_snippet())
    if "gazebo" in active_adapter_ids:
        snippets.append(get_gazebo_launch_snippet())

    for c in plan.components:
        if not c.has_adapter or not c.adapter_name:
            generic_comments.append(
                f"    # Component: {c.name} ({c.resource_id}) - Add custom node/include below if required"
            )

    body_snippets = "\n".join(snippets) if snippets else "    # No dedicated verified launch adapters active"
    generic_comments_str = "\n".join(generic_comments) if generic_comments else "    # All components mapped to verified launch adapters"

    pkg_name = plan.bringup_package_name

    launch_code = f"""# Auto-generated by OpenRobo Workspace Generator
# Stack: {plan.stack_name} (Target ROS: {plan.target_distro}, OS: {plan.target_os})
# Evidence: Deterministically synthesized via OpenRobo Adapter Registry

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, LogInfo
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    ld = LaunchDescription()

    # Declare Launch Arguments
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    declare_sim_time_arg = DeclareLaunchArgument(
        'use_sim_time',
        default_value='true',
        description='Use simulation (Gazebo) clock if true'
    )
    ld.add_action(declare_sim_time_arg)

    bringup_share = get_package_share_directory('{pkg_name}')

    # Log bringup startup
    ld.add_action(LogInfo(msg='Starting OpenRobo Autonomous Bringup Pipeline for {plan.stack_name}...'))

{body_snippets}

{generic_comments_str}

    return ld
"""

    return GeneratedFile(
        path=f"src/{pkg_name}/launch/robot_bringup.launch.py",
        content=launch_code,
        is_executable=True,
        description=f"Main ROS 2 launch orchestration entrypoint for {pkg_name}",
    )
