"""Composite Bringup Launch Generator."""

from openrobo_workspace.adapters.gazebo import get_gazebo_launch_snippet
from openrobo_workspace.adapters.nav2 import get_nav2_launch_snippet
from openrobo_workspace.adapters.ros2_control import get_ros2_control_launch_snippet
from openrobo_workspace.adapters.slam_toolbox import get_slam_toolbox_launch_snippet
from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan


def generate_bringup_launch(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    component_ids = {c.resource_id.lower() for c in plan.components}

    snippets = []
    generic_comments = []

    has_nav2 = any("nav2" in cid or "navigation2" in cid for cid in component_ids)
    has_slam = any("slam_toolbox" in cid or "slam-toolbox" in cid for cid in component_ids)
    has_control = any("ros2_control" in cid or "joint_state_broadcaster" in cid for cid in component_ids)
    has_gazebo = any("gazebo" in cid or "gz_sim" in cid or "ros_gz" in cid for cid in component_ids)

    if has_control:
        snippets.append(get_ros2_control_launch_snippet())
    if has_slam:
        snippets.append(get_slam_toolbox_launch_snippet())
    if has_nav2:
        snippets.append(get_nav2_launch_snippet())
    if has_gazebo:
        snippets.append(get_gazebo_launch_snippet())

    for c in plan.components:
        cid = c.resource_id.lower()
        if not ("nav2" in cid or "slam_toolbox" in cid or "ros2_control" in cid or "gazebo" in cid or "gz_sim" in cid or "ros_gz" in cid):
            generic_comments.append(
                f"    # Component: {c.name} ({c.resource_id}) - Add custom node/include below if required"
            )

    body_snippets = "\n".join(snippets) if snippets else "    # No dedicated verified launch adapters active"
    generic_comments_str = "\n".join(generic_comments) if generic_comments else "    # All components mapped to verified launch adapters"

    pkg_name = plan.bringup_package_name

    launch_code = f"""# Auto-generated by OpenRobo Workspace Generator
# Stack: {plan.stack_name} (Target ROS: {plan.target_distro}, OS: {plan.target_os})

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, LogInfo
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    ld = LaunchDescription()

    # Declare Launch Arguments
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    declare_sim_time_arg = DeclareLaunchArgument(
        'use_sim_time',
        default_value='true',
        description='Use simulation (Gazebo) clock if true'
    )
    ld.add_action(declare_sim_time_arg)

    bringup_share = get_package_share_directory('{pkg_name}')

    # Log bringup startup
    ld.add_action(LogInfo(msg='Starting OpenRobo Autonomous Bringup Pipeline for {plan.stack_name}...'))

{body_snippets}

{generic_comments_str}

    return ld
"""

    return GeneratedFile(
        path=f"src/{pkg_name}/launch/robot_bringup.launch.py",
        content=launch_code,
        is_executable=True,
        description=f"Main ROS 2 launch orchestration entrypoint for {pkg_name}",
    )
