"""ROS dependency and environment setup scripts generator (Hardened)."""

import re
import shlex

from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan

DEB_PKG_REGEX = re.compile(r"^[a-z0-9][a-z0-9+\-.]+$")
PIP_PKG_REGEX = re.compile(r"^[a-zA-Z0-9_\-\.><=~!^, ]+$")
DISTRO_REGEX = re.compile(r"^[a-z0-9_]+$")


def validate_debian_package_name(pkg_name: str) -> bool:
    """Validate Debian/Ubuntu APT package name to prevent shell injection."""
    return bool(DEB_PKG_REGEX.match(pkg_name.strip()))


def validate_pip_requirement(pkg_req: str) -> bool:
    """Validate pip package requirement specifier to prevent shell injection."""
    clean = pkg_req.strip()
    return bool(PIP_PKG_REGEX.match(clean)) and not any(c in clean for c in "\n\r\t;$`&|<>")


def generate_rosdep_install_sh(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    distro = plan.target_distro.strip().lower()
    if not DISTRO_REGEX.match(distro):
        raise ValueError(f"Invalid ROS distribution name: '{distro}'")

    safe_distro = shlex.quote(distro)

    content = [
        "#!/usr/bin/env bash",
        "# Generated by OpenRobo Workspace Generator",
        "# Script: rosdep installation & resolution",
        "set -euo pipefail",
        "",
        "echo '=== [OpenRobo] Updating rosdep sources ==='",
        "sudo rosdep init 2>/dev/null || true",
        "rosdep update --include-eol-distros || rosdep update",
        "",
        f"echo '=== [OpenRobo] Installing dependencies for target distro: {safe_distro} ==='",
        'if [ -d "src" ]; then',
        f"  rosdep install --from-paths src --ignore-src --rosdistro {safe_distro} -y -r",
        "else",
        '  echo "No src/ directory found. Skipping --from-paths rosdep install."',
        "fi",
        "",
        "echo '=== [OpenRobo] rosdep dependency resolution complete ==='",
        "",
    ]
    return GeneratedFile(path="setup/rosdep-install.sh", content="\n".join(content), is_executable=True)


def generate_install_dependencies_sh(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by OpenRobo Workspace Generator",
        "# Script: System & Python dependencies setup",
        "set -euo pipefail",
        "",
        "echo '=== [OpenRobo] Installing System Dependencies (APT) ==='",
        "sudo apt-get update -y",
        "sudo apt-get install -y --no-install-recommends \\",
        "  build-essential \\",
        "  cmake \\",
        "  git \\",
        "  python3-colcon-common-extensions \\",
        "  python3-rosdep \\",
        "  python3-pip",
    ]

    for dep in sorted(set(plan.system_dependencies)):
        clean_dep = dep.strip()
        if validate_debian_package_name(clean_dep):
            lines.append(f"sudo apt-get install -y --no-install-recommends {shlex.quote(clean_dep)}")
        else:
            lines.append(f"# WARNING: Ignored unsafe system dependency name: '{clean_dep}'")

    if plan.python_dependencies:
        lines.append("")
        lines.append("echo '=== [OpenRobo] Installing Python Dependencies (pip) ==='")
        for py_dep in sorted(set(plan.python_dependencies)):
            clean_py = py_dep.strip()
            if validate_pip_requirement(clean_py):
                lines.append(f"python3 -m pip install --no-cache-dir {shlex.quote(clean_py)}")
            else:
                lines.append(f"# WARNING: Ignored unsafe python package name: '{clean_py}'")

    lines.append("")
    lines.append("echo '=== [OpenRobo] System dependencies installed successfully ==='")
    lines.append("")
    return GeneratedFile(path="setup/install_dependencies.sh", content="\n".join(lines), is_executable=True)


def generate_install_dependencies_ps1(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    lines = [
        "# Generated by OpenRobo Workspace Generator",
        "# Script: Windows / Containerized Dependency Helper",
        "$ErrorActionPreference = 'Stop'",
        "",
        f"Write-Host '=== [OpenRobo] Dependency Setup for {plan.target_distro} ===' -ForegroundColor Cyan",
        f"Write-Host 'Target OS: {plan.target_os} ({plan.target_arch})'",
        "Write-Host 'Note: For native Linux ROS 2 environments or WSL2 / Dev Container, use setup/install_dependencies.sh.'",
        "",
    ]

    if plan.python_dependencies:
        lines.append("Write-Host 'Installing Python packages via pip...'")
        for py_dep in sorted(set(plan.python_dependencies)):
            clean_py = py_dep.strip()
            if validate_pip_requirement(clean_py):
                # Escape single quotes for PowerShell
                ps_safe = clean_py.replace("'", "''")
                lines.append(f"python -m pip install --no-cache-dir '{ps_safe}'")
            else:
                lines.append(f"# WARNING: Ignored unsafe python package name: '{clean_py}'")

    lines.append("")
    lines.append("Write-Host '=== [OpenRobo] Setup script completed ===' -ForegroundColor Green")
    lines.append("")
    return GeneratedFile(path="setup/install_dependencies.ps1", content="\n".join(lines), is_executable=False)
