"""ROS dependency and environment setup scripts generator."""

from openrobo_workspace.models import GeneratedFile, WorkspaceGenerationPlan


def generate_rosdep_install_sh(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    content = [
        "#!/usr/bin/env bash",
        "# Generated by OpenRobo Workspace Generator",
        "# Script: rosdep installation & resolution",
        "set -euo pipefail",
        "",
        "echo '=== [OpenRobo] Updating rosdep sources ==='",
        "sudo rosdep init 2>/dev/null || true",
        "rosdep update --include-eol-distros || rosdep update",
        "",
        f"echo '=== [OpenRobo] Installing dependencies for target distro: {plan.target_distro} ==='",
        'if [ -d "src" ]; then',
        f'  rosdep install --from-paths src --ignore-src --rosdistro "{plan.target_distro}" -y -r',
        "else",
        '  echo "No src/ directory found. Skipping --from-paths rosdep install."',
        "fi",
        "",
        "echo '=== [OpenRobo] rosdep dependency resolution complete ==='",
        "",
    ]
    return GeneratedFile(path="setup/rosdep-install.sh", content="\n".join(content), is_executable=True)


def generate_install_dependencies_sh(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by OpenRobo Workspace Generator",
        "# Script: System & Python dependencies setup",
        "set -euo pipefail",
        "",
        "echo '=== [OpenRobo] Installing System Dependencies (APT) ==='",
        "sudo apt-get update -y",
        "sudo apt-get install -y --no-install-recommends \\",
        "  build-essential \\",
        "  cmake \\",
        "  git \\",
        "  python3-colcon-common-extensions \\",
        "  python3-rosdep \\",
        "  python3-pip",
    ]
    if plan.system_dependencies:
        for dep in sorted(set(plan.system_dependencies)):
            lines.append(f"sudo apt-get install -y --no-install-recommends {dep}")

    if plan.python_dependencies:
        lines.append("")
        lines.append("echo '=== [OpenRobo] Installing Python Dependencies (pip) ==='")
        for py_dep in sorted(set(plan.python_dependencies)):
            lines.append(f'python3 -m pip install --no-cache-dir "{py_dep}"')

    lines.append("")
    lines.append("echo '=== [OpenRobo] System dependencies installed successfully ==='")
    lines.append("")
    return GeneratedFile(path="setup/install_dependencies.sh", content="\n".join(lines), is_executable=True)


def generate_install_dependencies_ps1(plan: WorkspaceGenerationPlan) -> GeneratedFile:
    lines = [
        "# Generated by OpenRobo Workspace Generator",
        "# Script: Windows / Containerized Dependency Helper",
        "$ErrorActionPreference = 'Stop'",
        "",
        f"Write-Host '=== [OpenRobo] Dependency Setup for {plan.target_distro} ===' -ForegroundColor Cyan",
        f"Write-Host 'Target OS: {plan.target_os} ({plan.target_arch})'",
        "Write-Host 'Note: For native Linux ROS 2 environments or WSL2 / Dev Container, use setup/install_dependencies.sh.'",
        "",
    ]
    if plan.python_dependencies:
        lines.append("Write-Host 'Installing Python packages via pip...'")
        for py_dep in sorted(set(plan.python_dependencies)):
            lines.append(f'python -m pip install --no-cache-dir "{py_dep}"')

    lines.append("")
    lines.append("Write-Host '=== [OpenRobo] Setup script completed ===' -ForegroundColor Green")
    lines.append("")
    return GeneratedFile(path="setup/install_dependencies.ps1", content="\n".join(lines), is_executable=False)
